name: main

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.name }}

    strategy:
      matrix:
        include:
        - name: flake8
          python: 3.8

        - name: py36-dj22
          python: 3.6

        - name: py37-dj22
          python: 3.7

        - name: py37-dj30
          python: 3.7

        - name: py38-dj30
          python: 3.8

        - name: py38-dj31
          python: 3.8

        - name: py39-dj31
          python: 3.9
